name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6f1c1053b4cf6cc2938acaa4956eb94ab579217d343ac5f2b4c077d7d6bcafb"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
