name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f3a62632c858e1e9175f99e15eddf176cc2f9df876ac885f3cf07fcb2976f34"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
